version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./nactranslate
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"     # for the react app
      - "8000:8000" # for the WebSocket connection
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
